# Generated by Django 4.1.10 on 2023-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("DocumentClassification", "Document Classification"),
                    ("SequenceLabeling", "Sequence Labeling"),
                    ("Seq2seq", "Seq2Seq"),
                    ("IntentDetectionAndSlotFilling", "Intent Detection And Slot Filling"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="BoundingBoxProject",
        ),
        migrations.DeleteModel(
            name="ImageCaptioningProject",
        ),
        migrations.DeleteModel(
            name="ImageClassificationProject",
        ),
        migrations.DeleteModel(
            name="SegmentationProject",
        ),
        migrations.DeleteModel(
            name="Speech2textProject",
        ),
    ]
