# Generated by Django 4.1.10 on 2023-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_remove_imagecaptioningproject_project_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_state",
            field=models.CharField(
                choices=[
                    ("HownetRuleDeveloping", "Hownet Rule Developing"),
                    ("HownetRuleCommitted", "Hownet Rule Committed"),
                    ("AnnotateManually", "Annotate Manually"),
                ],
                default="AnnotateManually",
                max_length=50,
            ),
        ),
    ]
