# Generated by Django 4.1.10 on 2023-10-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0016_segmentation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segmentation",
            name="example",
        ),
        migrations.RemoveField(
            model_name="segmentation",
            name="label",
        ),
        migrations.RemoveField(
            model_name="segmentation",
            name="user",
        ),
        migrations.DeleteModel(
            name="BoundingBox",
        ),
        migrations.DeleteModel(
            name="Segmentation",
        ),
    ]
