# Generated by Django 4.1.10 on 2023-10-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_export", "0004_exportedcomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExportedBoundingBox",
        ),
        migrations.DeleteModel(
            name="ExportedSegmentation",
        ),
    ]
